name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
	script: |
	  DIR='/home/isucon/isucon10'
          $DIR/deploy/notify.sh "== deploy start =="
          cd $DIR/deploy
          git pull
          sudo systemctl restart mysql
          sudo systemctl restart nginx
          $DIR/deploy/notify.sh "== deploy end =="
